# Generated by Django 6.0.3 on 2026-05-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_delete_companyoauthredirect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyoauthclient',
            options={'ordering': ['social_app__provider', 'social_app__name', 'id']},
        ),
    ]
