# Generated by Django 6.0.3 on 2026-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_access_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_mode',
            field=models.CharField(choices=[('public', 'Public'), ('domain', 'Domain'), ('invite', 'Invitation only')], default='public', help_text='How new OAuth users join: Public (open), Domain (email allow list), or Invitation only (admin must enable the user).', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='allowed_email_domains',
            field=models.JSONField(blank=True, default=list, help_text='Lowercase domains without @ (e.g. ["acme.com"]). Used when access mode is Domain.'),
        ),
    ]
