# Generated by Django 6.0.8 on 2026-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_enable_magic_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygroup',
            name='display_name',
            field=models.CharField(help_text='SCIM displayName (unique per company).', max_length=150),
        ),
    ]
