# Generated by Django 6.0.8 on 2026-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_verified_email_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enable_magic_link',
            field=models.BooleanField(default=True, help_text='When true (default for new companies), users can request passwordless email magic links for this company. Requires deployment MAGIC_LINK_ENABLED.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='verified_email_domains',
            field=models.JSONField(blank=True, default=list, help_text='Domains Shellui operators have confirmed this company owns (Django admin only). SAML may link by assertion email only on these domains when the IdP is trusted. Company admins cannot set this via the Shellui admin API.'),
        ),
    ]
