# Generated by Django 6.0.8 on 2026-10-02 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_company_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data_retention_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days to keep the event log and finished webhook deliveries before "manage.py purge_expired_data" deletes them. Django admin only.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
    ]
