# Generated by Django 6.0.8 on 2026-09-26 06:24

import apps.actions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionoutbox',
            options={'ordering': ['-created_at'], 'verbose_name': 'Action delivery', 'verbose_name_plural': 'Action deliveries'},
        ),
        migrations.AlterModelOptions(
            name='deliveryattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivery attempt', 'verbose_name_plural': 'Delivery attempts'},
        ),
        migrations.AlterField(
            model_name='actionrule',
            name='event_type',
            field=models.CharField(choices=apps.actions.models._event_type_field_choices, max_length=128),
        ),
    ]
