# Generated by Django 6.0.8 on 2026-09-29 07:49

from django.db import migrations, models


def delete_email_action_rules(apps, schema_editor):
    ActionRule = apps.get_model('actions', 'ActionRule')
    ActionRule.objects.filter(action_kind='email').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_actionoutbox_options_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_email_action_rules, migrations.RunPython.noop),
        migrations.AddField(
            model_name='actionoutbox',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionrule',
            name='action_kind',
            field=models.CharField(choices=[('webhook', 'Webhook')], default='webhook', max_length=16),
        ),
    ]
