# Generated by Django 6.0.8 on 2026-10-02 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_webhooks_only_and_locked_until'),
        ('companies', '0025_company_data_retention_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event log entry',
                'verbose_name_plural': 'Event log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='actions_eventlog_company_idx'), models.Index(fields=['user', '-created_at'], name='actions_eventlog_user_idx')],
            },
        ),
    ]
