# Generated by Django 6.0.8 on 2026-10-02 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_copy_login_events'),
        ('companies', '0025_company_data_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('body', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_event_outbox_rows', to='companies.company')),
            ],
            options={
                'verbose_name': 'Email event delivery',
                'verbose_name_plural': 'Email event deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='actions_ema_status_edda27_idx')],
            },
        ),
    ]
