# Generated by Django 6.0.3 on 2026-05-06 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0007_rename_metrics_api_key_to_api_access_token'),
        ('companies', '0008_metrics_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=255)),
                ('read_only', models.BooleanField(default=False, help_text='If True, only safe HTTP methods are allowed when this PAT is used.')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personal access token',
                'verbose_name_plural': 'Personal access tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='apiaccesstoken',
            name='authapi_met_company_847f5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiaccesstoken',
            name='authapi_met_user_id_9a077f_idx',
        ),
        migrations.AddField(
            model_name='personalaccesstoken',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_access_tokens', to='companies.company'),
        ),
        migrations.AddField(
            model_name='personalaccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='apiaccesstoken',
            name='company',
        ),
        migrations.RemoveField(
            model_name='apiaccesstoken',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apiaccesstoken',
            name='user',
        ),
        migrations.AddIndex(
            model_name='personalaccesstoken',
            index=models.Index(fields=['company', '-created_at'], name='authapi_per_company_129914_idx'),
        ),
        migrations.AddIndex(
            model_name='personalaccesstoken',
            index=models.Index(fields=['user', '-created_at'], name='authapi_per_user_id_d53612_idx'),
        ),
        migrations.DeleteModel(
            name='ApiAccessToken',
        ),
    ]
