# Generated by Django 6.0.3 on 2026-05-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0008_personal_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccesstoken',
            name='access_global_metrics',
            field=models.BooleanField(default=False, help_text='If True, PAT may call GET /api/v1/metrics/all (cross-company). Only staff may enable.'),
        ),
    ]
