# Generated by Django 6.0.8 on 2026-09-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0011_magic_link_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='magiclinktoken',
            new_name='authapi_mag_company_ab6619_idx',
            old_name='authapi_mag_company_6e1a2b_idx',
        ),
    ]
