# Generated by Django 6.0.8 on 2026-10-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0015_scope_self_hosted_gitlab_uids'),
        ('actions', '0005_copy_login_events'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginevent',
            name='authapi_log_user_id_07022b_idx',
        ),
        migrations.DeleteModel(
            name='LoginEvent',
        ),
    ]
