# Generated by Django 6.0.8 on 2026-09-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0003_scim_provisioning_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyscimtoken',
            new_name='scim_compan_company_dc3729_idx',
            old_name='scim_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='scimprovisioningevent',
            new_name='scim_scimpr_company_ff4739_idx',
            old_name='scim_scimpr_company_6a8b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='scimprovisioningevent',
            new_name='scim_scimpr_company_4112f8_idx',
            old_name='scim_scimpr_company_2f4c91_idx',
        ),
    ]
