from django.urls import path

from .views import (
    ShellUIAdminGroupDetailView,
    ShellUIAdminGroupListView,
    ShellUIAdminLoginEventDetailView,
    ShellUIAdminLoginEventListView,
    ShellUIAdminOAuthClientDetailView,
    ShellUIAdminOAuthClientListView,
    ShellUIAdminOAuthSocialAppDetailView,
    ShellUIAdminOAuthSocialAppListView,
    ShellUIPersonalAccessTokenListCreateView,
    ShellUIPersonalAccessTokenRevokeView,
    ShellUIAdminGlobalMetricsView,
    ShellUIAdminMetricsView,
    ShellUIAdminUserDetailView,
    ShellUIAdminUserListView,
    ShellUIAuthSettingsView,
    ShellUIAuthorizeView,
    ShellUILogoutView,
    ShellUIOAuthExchangeView,
    ShellUIOAuthCallbackView,
    ShellUIPreferenceView,
    ShellUITokenView,
    ShellUIUserView,
    SocialAuthorizeView,
    SocialLoginView,
)

urlpatterns = [
    path('settings', ShellUIAuthSettingsView.as_view(), name='shellui-settings'),
    path('authorize', ShellUIAuthorizeView.as_view(), name='shellui-authorize'),
    path('oauth/callback', ShellUIOAuthCallbackView.as_view(), name='shellui-oauth-callback'),
    path('oauth/exchange', ShellUIOAuthExchangeView.as_view(), name='shellui-oauth-exchange'),
    path('token', ShellUITokenView.as_view(), name='shellui-token'),
    path('logout', ShellUILogoutView.as_view(), name='shellui-logout'),
    path('user', ShellUIUserView.as_view(), name='shellui-user'),
    path('groups', ShellUIAdminGroupListView.as_view(), name='shellui-admin-groups'),
    path('groups/<int:pk>', ShellUIAdminGroupDetailView.as_view(), name='shellui-admin-group-detail'),
    path('users', ShellUIAdminUserListView.as_view(), name='shellui-admin-users'),
    path('login-events', ShellUIAdminLoginEventListView.as_view(), name='shellui-admin-login-events'),
    path('login-events/<int:pk>', ShellUIAdminLoginEventDetailView.as_view(), name='shellui-admin-login-event-detail'),
    path('oauth-clients', ShellUIAdminOAuthClientListView.as_view(), name='shellui-admin-oauth-clients'),
    path('oauth-clients/<int:pk>', ShellUIAdminOAuthClientDetailView.as_view(), name='shellui-admin-oauth-client-detail'),
    path('oauth-social-apps', ShellUIAdminOAuthSocialAppListView.as_view(), name='shellui-admin-oauth-social-apps'),
    path('oauth-social-apps/<int:pk>', ShellUIAdminOAuthSocialAppDetailView.as_view(), name='shellui-admin-oauth-social-app-detail'),
    path('metrics', ShellUIAdminMetricsView.as_view(), name='shellui-admin-metrics'),
    path('metrics/all', ShellUIAdminGlobalMetricsView.as_view(), name='shellui-admin-metrics-all'),
    path(
        'personal-access-tokens/<uuid:key_id>/revoke',
        ShellUIPersonalAccessTokenRevokeView.as_view(),
        name='shellui-personal-access-token-revoke',
    ),
    path(
        'personal-access-tokens',
        ShellUIPersonalAccessTokenListCreateView.as_view(),
        name='shellui-personal-access-tokens',
    ),
    path('users/<int:pk>', ShellUIAdminUserDetailView.as_view(), name='shellui-admin-user-detail'),
    path('preferences', ShellUIPreferenceView.as_view(), name='shellui-preferences'),
    path('providers/<str:provider>/authorize/', SocialAuthorizeView.as_view(), name='social-authorize'),
    path('providers/<str:provider>/login/', SocialLoginView.as_view(), name='social-login'),
]
