"""Installed django-allauth socialaccount provider apps (generated)."""

# Generated by tools/generate_allauth_provider_apps.py — do not edit by hand.
ALLAUTH_SOCIALACCOUNT_PROVIDER_APPS: tuple[str, ...] = (
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
)
