"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
import re
import sys
import tomllib
from pathlib import Path
from datetime import timedelta

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

from apps.authapi.jwks import read_jwt_env, resolve_jwt_configuration
from config.allauth_provider_apps import ALLAUTH_SOCIALACCOUNT_PROVIDER_APPS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _env_csv(name, default):
    raw = os.getenv(name, '').strip()
    if not raw:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


_DURATION_RE = re.compile(r'^(\d+(?:\.\d+)?)(s|m|h|d)?$', re.IGNORECASE)
_DURATION_UNITS = {
    's': 1,
    'm': 60,
    'h': 3600,
    'd': 86400,
}


def _env_duration(name, default):
    """
    Parse JWT-style lifetimes from env.

    Supported forms: ``30s``, ``5m``, ``2h``, ``7d``, or a bare integer (seconds).
    """
    raw = os.getenv(name, '').strip()
    if not raw:
        return default
    match = _DURATION_RE.fullmatch(raw)
    if not match:
        raise ImproperlyConfigured(
            f'{name} must be a duration like 30s, 5m, 2h, or 7d (bare integer = seconds). '
            f'Got: {raw!r}'
        )
    amount = float(match.group(1))
    unit = (match.group(2) or 's').lower()
    if amount <= 0:
        raise ImproperlyConfigured(f'{name} must be greater than zero. Got: {raw!r}')
    return timedelta(seconds=amount * _DURATION_UNITS[unit])


def _env_float(name, default):
    raw = os.getenv(name, '').strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be a number. Got: {raw!r}') from exc


def _env_bool(name, default: bool) -> bool:
    raw = os.getenv(name, '').strip()
    if not raw:
        return default
    return raw.lower() in {'1', 'true', 'yes', 'on'}


def _env_int(name, default: int) -> int:
    raw = os.getenv(name, '').strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer. Got: {raw!r}') from exc


def _env_positive_float(name, default):
    value = _env_float(name, default)
    if value <= 0:
        raise ImproperlyConfigured(f'{name} must be greater than zero. Got: {value!r}')
    return value


def _env_non_negative_float(name, default):
    value = _env_float(name, default)
    if value < 0:
        raise ImproperlyConfigured(f'{name} must be zero or greater. Got: {value!r}')
    return value


def _postgres_timeout_options(statement_timeout: float, lock_timeout: float) -> str:
    """
    Build the libpq ``options`` string that sets server-side query deadlines.

    Values are in seconds. 0 turns a deadline off. Postgres expects milliseconds.
    """
    parts = []
    if statement_timeout > 0:
        parts.append(f'-c statement_timeout={int(statement_timeout * 1000)}')
    if lock_timeout > 0:
        parts.append(f'-c lock_timeout={int(lock_timeout * 1000)}')
    return ' '.join(parts)


def _running_management_command(*names: str) -> bool:
    return len(sys.argv) > 1 and sys.argv[1] in names


def _caches_config(redis_url: str) -> dict:
    """
    Shared cache for auth rate limits, access-token denylist, and activity throttles.

    When ``REDIS_URL`` is set, use Django's Redis backend (requires the ``redis`` package).
    Otherwise use in-process LocMem (fine for single-process dev; not shared across Gunicorn workers).
    """
    if redis_url:
        return {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_url,
            }
        }
    return {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'identity-service-auth',
        }
    }


def _celery_broker_url(redis_url: str, override: str) -> str:
    """Broker for the scheduled jobs: ``CELERY_BROKER_URL`` when set, else ``REDIS_URL``."""
    return (override or '').strip() or (redis_url or '').strip()


def scheduled_jobs_beat_schedule() -> dict:
    """
    Celery beat entries for the scheduled jobs.

    ``expires`` drops a message that waited longer than its period (worker down or
    busy), so a backlog never turns into a burst of runs.
    """
    from celery.schedules import crontab

    return {
        'retry-webhooks': {
            'task': 'actions.retry_webhooks',
            'schedule': timedelta(seconds=60),
            'options': {'expires': 55},
        },
        'purge-expired-data': {
            'task': 'actions.purge_expired_data',
            # Hourly at minute 17: off the top of the hour, where many jobs start.
            'schedule': crontab(minute=17),
            'options': {'expires': 3000},
        },
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv('SECRET_KEY', '').strip()
if not _secret_key:
    raise ImproperlyConfigured(
        '\n'
        'SECRET_KEY is not set — identity-service cannot start.\n'
        '\n'
        'Django uses this value to sign sessions and CSRF tokens. '
        'When JWT_PRIVATE_KEY is set, JWTs are signed with RS256 instead.\n'
        '\n'
        'How to fix:\n'
        '  1. Copy the example env file:\n'
        '       cp .env.example .env\n'
        '  2. Set SECRET_KEY in .env (or export it in your shell).\n'
        '  3. Generate a strong key:\n'
        '       python -c "from django.core.management.utils import '
        'get_random_secret_key; print(get_random_secret_key())"\n'
        '\n'
        'With Docker Compose, define SECRET_KEY in your .env file before '
        'running docker compose up.\n'
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').strip().lower() in {'1', 'true', 'yes', 'on'}

# One-time web bootstrap token for creating the first superuser when DEBUG=false.
# When unset, use `manage.py createsuperuser` instead of the public form at `/`.
SETUP_TOKEN = os.getenv('SETUP_TOKEN', '').strip()

# Comma-separated; use * for all hosts only in trusted networks. Example: app.example.com,127.0.0.1
ALLOWED_HOSTS = _env_csv('ALLOWED_HOSTS', ('localhost', '127.0.0.1'))
# Full origins with scheme (required for cross-site POST / CSRF). Example: https://app.example.com
CSRF_TRUSTED_ORIGINS = _env_csv(
    'CSRF_TRUSTED_ORIGINS',
    (
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:4000',
        'http://127.0.0.1:4000',
        'http://localhost:5174',
        'http://127.0.0.1:5174',
        'https://admin.shellui.com',
    ),
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Trusted reverse proxies (comma-separated IPs/CIDRs). X-Forwarded-For is honored for audit IP
# only when REMOTE_ADDR matches one of these entries. See docs/security-hardening.md.
TRUSTED_PROXY_IPS = _env_csv('TRUSTED_PROXY_IPS', ())

# Self-service DELETE /api/v1/user: access JWT ``iat`` must be within this age (not PATs).
SELF_SERVICE_ACCOUNT_DELETE_MAX_IAT_AGE = _env_duration(
    'SELF_SERVICE_ACCOUNT_DELETE_MAX_IAT_AGE',
    timedelta(minutes=5),
)

# Loopback OAuth redirect targets (127.0.0.1 / localhost / ::1) are allowed only when DEBUG or
# OAUTH_ALLOW_LOOPBACK_REDIRECTS=true (local CLI / dev shells).
OAUTH_ALLOW_LOOPBACK_REDIRECTS = _env_bool('OAUTH_ALLOW_LOOPBACK_REDIRECTS', DEBUG)


def _project_version():
    pyproject = BASE_DIR / 'pyproject.toml'
    with pyproject.open('rb') as fh:
        data = tomllib.load(fh)
    version = str(data.get('project', {}).get('version', '')).strip()
    if not version:
        raise ImproperlyConfigured(f'project.version is missing in {pyproject}')
    return version


VERSION = _project_version()

SCIM_ENABLED = _env_bool('SCIM_ENABLED', True)

# Logging: always write to stdout (Docker / Coolify logs), also when DEBUG=false.
LOG_LEVEL = os.getenv('LOG_LEVEL', '').strip().upper() or ('DEBUG' if DEBUG else 'INFO')
if LOG_LEVEL not in {'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'}:
    raise ImproperlyConfigured(
        f'LOG_LEVEL must be DEBUG, INFO, WARNING, ERROR or CRITICAL. Got: {LOG_LEVEL!r}'
    )
# Requests slower than this many seconds are logged as a warning. 0 turns it off.
SLOW_REQUEST_THRESHOLD_SECONDS = _env_non_negative_float('SLOW_REQUEST_THRESHOLD_SECONDS', 2.0)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    *ALLAUTH_SOCIALACCOUNT_PROVIDER_APPS,
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'apps.authapi',
    'apps.companies',
    'apps.scim',
    'apps.actions',
    'django_scim',
    'config.apps.ConfigConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.authapi.authentication.ShellUIJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.authapi.permissions.ShellUIPermission',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Shellui Auth API',
    'DESCRIPTION': (
        'API documentation. Use **Authorize** and enter `Bearer <token>` or paste the raw JWT; '
        'Swagger sends `Authorization: Bearer …` for operations that require **bearerAuth**.'
    ),
    'VERSION': VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'TAGS': [
        {'name': 'auth-session', 'description': 'Session lifecycle endpoints (settings, token refresh, logout, JWKS).'},
        {'name': 'auth-social', 'description': 'OAuth/social login flow endpoints.'},
        {'name': 'auth-profile', 'description': 'Current authenticated user profile and metadata.'},
        {'name': 'auth-preferences', 'description': 'Current authenticated user preferences.'},
        {'name': 'directory-users', 'description': 'User directory management for staff/company owners.'},
        {'name': 'directory-groups', 'description': 'Group management for staff/company owners.'},
        {'name': 'oauth-clients', 'description': 'Company OAuth client mappings.'},
        {'name': 'oauth-social-apps', 'description': 'SocialApp key catalog and setup flows.'},
        {'name': 'audit-events', 'description': 'Login audit events and filters.'},
        {'name': 'platform-metrics', 'description': 'Prometheus metrics endpoints.'},
        {'name': 'personal-access-tokens', 'description': 'User-personal JWT access tokens (read-only or read/write).'},
        {'name': 'companies', 'description': 'Company membership and company settings endpoints.'},
    ],
}

MIDDLEWARE = [
    'config.request_context.RequestIdMiddleware',
    'apps.authapi.middleware.LivenessMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.authapi.middleware.AdminLoginRateLimitMiddleware',
]

_auth_middleware_index = MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware')
MIDDLEWARE.insert(_auth_middleware_index + 1, 'apps.scim.middleware.ScimBearerAuthMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}

SOCIALACCOUNT_ADAPTER = 'apps.authapi.social_account_adapter.ShellUISocialAccountAdapter'

# Transactional email (company access requests / enable notifications).
# Local default: print to console. Production: set EMAIL_HOST / EMAIL_BACKEND.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'config.email_backends.ConsoleEmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25') or '25')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'false').strip().lower() in {'1', 'true', 'yes', 'on'}
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').strip().lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@localhost')
# Seconds before an SMTP connect, read or write gives up. Django's default is no timeout,
# so an unreachable mail server could hold a login request forever.
EMAIL_TIMEOUT = _env_positive_float('EMAIL_TIMEOUT', 10.0)

# Shellui email-service. Unset EMAIL_SERVICE_API_KEY keeps the SMTP / console backend.
EMAIL_SERVICE_URL = (
    os.getenv('EMAIL_SERVICE_URL', 'https://email.shellui.com').strip() or 'https://email.shellui.com'
).rstrip('/')
EMAIL_SERVICE_API_KEY = os.getenv('EMAIL_SERVICE_API_KEY', '').strip()
EMAIL_SERVICE_TIMEOUT_SECONDS = _env_float('EMAIL_SERVICE_TIMEOUT_SECONDS', 5.0)
EMAIL_SERVICE_SEND_ATTEMPTS = _env_int('EMAIL_SERVICE_SEND_ATTEMPTS', 3)
EMAIL_SERVICE_RETRY_MAX_SLEEP_SECONDS = _env_float('EMAIL_SERVICE_RETRY_MAX_SLEEP_SECONDS', 1.0)

# Shellui email-service. Unset EMAIL_SERVICE_API_KEY keeps the SMTP / console backend.
EMAIL_SERVICE_URL = (
    os.getenv('EMAIL_SERVICE_URL', 'https://email.shellui.com').strip() or 'https://email.shellui.com'
).rstrip('/')
EMAIL_SERVICE_API_KEY = os.getenv('EMAIL_SERVICE_API_KEY', '').strip()
EMAIL_SERVICE_TIMEOUT_SECONDS = _env_float('EMAIL_SERVICE_TIMEOUT_SECONDS', 5.0)
EMAIL_SERVICE_SEND_ATTEMPTS = _env_int('EMAIL_SERVICE_SEND_ATTEMPTS', 3)
EMAIL_SERVICE_RETRY_MAX_SLEEP_SECONDS = _env_float('EMAIL_SERVICE_RETRY_MAX_SLEEP_SECONDS', 1.0)

# Webhooks (domain events to HTTPS endpoints). DB outbox; retries run on the scheduler.
ACTIONS_WEBHOOK_TIMEOUT_SECONDS = _env_float('ACTIONS_WEBHOOK_TIMEOUT_SECONDS', 5.0)
ACTIONS_OUTBOX_MAX_ATTEMPTS = _env_int('ACTIONS_OUTBOX_MAX_ATTEMPTS', 8)
ACTIONS_WEBHOOK_ALLOW_PRIVATE = _env_bool('ACTIONS_WEBHOOK_ALLOW_PRIVATE', False)
ACTIONS_WEBHOOK_RETRY_LEASE_SECONDS = _env_int('ACTIONS_WEBHOOK_RETRY_LEASE_SECONDS', 120)
ACTIONS_WEBHOOK_DISPATCH_WORKERS = _env_int('ACTIONS_WEBHOOK_DISPATCH_WORKERS', 4)
ACTIONS_WEBHOOK_SYNC_DELIVERY = _env_bool('ACTIONS_WEBHOOK_SYNC_DELIVERY', False)
MAGIC_LINK_EMAIL_DEFAULT_LANGUAGE = (
    os.getenv('MAGIC_LINK_EMAIL_DEFAULT_LANGUAGE', 'en').strip().lower() or 'en'
)

JWT_ACCESS_TOKEN_LIFETIME = _env_duration('JWT_ACCESS_TOKEN_LIFETIME', timedelta(minutes=5))
JWT_REFRESH_TOKEN_LIFETIME = _env_duration('JWT_REFRESH_TOKEN_LIFETIME', timedelta(days=7))

JWT_ISSUER = os.getenv('JWT_ISSUER', '').strip() or None
JWT_AUDIENCE = os.getenv('JWT_AUDIENCE', '').strip() or None

# OAuth token delivery after login: ``code`` (one-time exchange, default) or ``fragment`` (legacy).
_oauth_delivery = os.getenv('OAUTH_TOKEN_DELIVERY', 'code').strip().lower()
if _oauth_delivery not in {'code', 'fragment'}:
    raise ImproperlyConfigured(
        'OAUTH_TOKEN_DELIVERY must be "code" or "fragment". '
        f'Got: {_oauth_delivery!r}'
    )
OAUTH_TOKEN_DELIVERY = _oauth_delivery
OAUTH_SESSION_CODE_TTL_SECONDS = int(os.getenv('OAUTH_SESSION_CODE_TTL_SECONDS', '120') or '120')

MAGIC_LINK_ENABLED = _env_bool('MAGIC_LINK_ENABLED', True)
MAGIC_LINK_TTL_SECONDS = int(os.getenv('MAGIC_LINK_TTL_SECONDS', '1800') or '1800')

# OAuth providers that skip the identity-hosted account confirmation page after callback.
# Unset env → ``google`` only. Set to empty string to require confirmation for all providers.
_skip_confirm_raw = os.getenv('OAUTH_SKIP_CONFIRM_PROVIDERS')
if _skip_confirm_raw is None:
    OAUTH_SKIP_CONFIRM_PROVIDERS = ['google']
else:
    OAUTH_SKIP_CONFIRM_PROVIDERS = [
        item.strip().lower() for item in _skip_confirm_raw.split(',') if item.strip()
    ]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': JWT_ACCESS_TOKEN_LIFETIME,
    'REFRESH_TOKEN_LIFETIME': JWT_REFRESH_TOKEN_LIFETIME,
    'ISSUER': JWT_ISSUER,
    'AUDIENCE': JWT_AUDIENCE,
}

_jwt_env = read_jwt_env()
_jwt_config = resolve_jwt_configuration(
    secret_key=SECRET_KEY,
    debug=DEBUG,
    **_jwt_env,
)
JWT_ALGORITHM = _jwt_config['algorithm']
JWT_ACTIVE_KEY_ID = _jwt_config['active_key_id']
JWT_SIGNING_KEY = _jwt_config['signing_key_obj']
JWT_PREVIOUS_VERIFYING_KEYS = _jwt_config['previous_verifying_keys']
JWT_ACCEPT_HS256_LEGACY = _jwt_config['accept_hs256_legacy']
JWKS_ENABLED = _jwt_config['jwks_enabled']
JWT_REQUIRES_RS256 = _jwt_config['requires_rs256']

SIMPLE_JWT.update(
    {
        'ALGORITHM': JWT_ALGORITHM,
        'SIGNING_KEY': _jwt_config['signing_key'],
        'VERIFYING_KEY': _jwt_config['verifying_key'],
    }
)

# Personal access tokens (PAT): JWT access token lifetime when creating a PAT (see views._issue_personal_access_token).
PERSONAL_ACCESS_TOKEN_LIFETIME = _env_duration('PERSONAL_ACCESS_TOKEN_LIFETIME', timedelta(days=30))

# Optional MaxMind GeoLite2/GeoIP2 City database (.mmdb) for login audit country/city.
# Install: uv add geoip2  — then set path to your .mmdb file.
SHELLUI_GEOIP_DATABASE_PATH = os.getenv('SHELLUI_GEOIP_DATABASE_PATH', '')

# OAuth credentials live per company on SocialApp rows (via CompanyOAuthClient).
# Scopes only — used by django-allauth provider modules and the admin UI.
SOCIALACCOUNT_PROVIDERS = {
    'github': {'SCOPE': ['read:user', 'user:email']},
    'twitch': {'SCOPE': ['user:read:email']},
    'google': {'SCOPE': ['openid', 'email', 'profile']},
    'microsoft': {
        'SCOPE': ['openid', 'email', 'profile', 'User.Read'],
        'TENANT': 'common',
    },
}

# API auth is Bearer JWT (not cookies). Multi-tenant shells run on unknown domains,
# so permissive CORS is intentional when CORS_ALLOW_CREDENTIALS=false (Supabase-style).
# Token delivery stays strict via CompanyOAuthRedirect (see docs/oauth-login.md).
CORS_ALLOW_ALL_ORIGINS = _env_bool('CORS_ALLOW_ALL_ORIGINS', True)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:4000',
    'http://127.0.0.1:4000',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'https://admin.shellui.com',
]
for _origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(','):
    _origin = _origin.strip()
    if _origin and _origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_origin)

CORS_ALLOWED_ORIGIN_REGEXES = []
for _pattern in os.getenv('CORS_ALLOWED_ORIGIN_REGEXES', '').split(','):
    _pattern = _pattern.strip()
    if _pattern and _pattern not in CORS_ALLOWED_ORIGIN_REGEXES:
        CORS_ALLOWED_ORIGIN_REGEXES.append(_pattern)

CORS_ALLOW_CREDENTIALS = _env_bool('CORS_ALLOW_CREDENTIALS', False)

if CORS_ALLOW_ALL_ORIGINS and CORS_ALLOW_CREDENTIALS:
    raise ImproperlyConfigured(
        'CORS_ALLOW_ALL_ORIGINS=true with CORS_ALLOW_CREDENTIALS=true is unsafe — '
        'use explicit CORS_ALLOWED_ORIGINS when credentials are enabled.'
    )

# HTTPS / cookie hardening (production defaults; override via env for local HTTP).
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)

# Cache-backed auth rate limits (see apps/authapi/throttling.py).
REDIS_URL = os.getenv('REDIS_URL', '').strip()
CACHES = _caches_config(REDIS_URL)
AUTH_RATE_LIMIT_ENABLED = _env_bool('AUTH_RATE_LIMIT_ENABLED', True)
AUTH_RATE_LIMITS = {
    'default': {'limit': 60, 'window': 60},
    'oauth': {'limit': _env_int('AUTH_RATE_LIMIT_OAUTH', 30), 'window': 60},
    'token_refresh': {'limit': _env_int('AUTH_RATE_LIMIT_TOKEN_REFRESH', 60), 'window': 60},
    'auth_settings': {'limit': _env_int('AUTH_RATE_LIMIT_SETTINGS', 30), 'window': 60},
    'admin_login': {'limit': _env_int('AUTH_RATE_LIMIT_ADMIN_LOGIN', 10), 'window': 300},
    'pat': {'limit': _env_int('AUTH_RATE_LIMIT_PAT', 30), 'window': 60},
    'magic_link': {'limit': _env_int('AUTH_RATE_LIMIT_MAGIC_LINK', 10), 'window': 60},
    'invitation': {'limit': _env_int('AUTH_RATE_LIMIT_INVITATION', 30), 'window': 300},
}

# Scheduled jobs (Celery worker + beat, started by the Docker entrypoint).
# See docs/scheduled-jobs.md. The broker is REDIS_URL unless CELERY_BROKER_URL is set.
# SCHEDULER_ENABLED is read by the entrypoint; it is here so tests and checks see it.
SCHEDULER_ENABLED = _env_bool('SCHEDULER_ENABLED', True)
CELERY_BROKER_URL = _celery_broker_url(REDIS_URL, os.getenv('CELERY_BROKER_URL', ''))
# Own queue and lock prefix, so services sharing one Redis never take each other's tasks.
CELERY_TASK_DEFAULT_QUEUE = 'identity-service'
SCHEDULER_LOCK_PREFIX = 'identity-service:scheduler'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_TASK_IGNORE_RESULT = True
CELERY_RESULT_EXPIRES = None
CELERY_RESULT_BACKEND = None
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_REDIRECT_STDOUTS = False
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = scheduled_jobs_beat_schedule()

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

POSTGRES_DATABASE_URL = os.getenv('POSTGRES_DATABASE_URL', '').strip()

if POSTGRES_DATABASE_URL:
    _postgres_ssl_require = _env_bool('POSTGRES_SSL_REQUIRE', not DEBUG)
    _postgres_connect_timeout = _env_int('POSTGRES_CONNECT_TIMEOUT', 10)
    # Server-side deadlines in seconds (0 turns one off). Not applied to `migrate`, so a
    # long migration at boot is not cut short.
    POSTGRES_STATEMENT_TIMEOUT = _env_non_negative_float('POSTGRES_STATEMENT_TIMEOUT', 15.0)
    POSTGRES_LOCK_TIMEOUT = _env_non_negative_float('POSTGRES_LOCK_TIMEOUT', 5.0)
    DATABASES = {
        'default': dj_database_url.parse(
            POSTGRES_DATABASE_URL,
            conn_max_age=600,
            ssl_require=_postgres_ssl_require,
        )
    }
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['connect_timeout'] = _postgres_connect_timeout
    if not _running_management_command('migrate'):
        _postgres_timeouts = _postgres_timeout_options(
            POSTGRES_STATEMENT_TIMEOUT,
            POSTGRES_LOCK_TIMEOUT,
        )
        if _postgres_timeouts:
            _existing_options = DATABASES['default']['OPTIONS'].get('options', '').strip()
            DATABASES['default']['OPTIONS']['options'] = ' '.join(
                part for part in (_existing_options, _postgres_timeouts) if part
            )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
            # Wait for the lock instead of failing immediately under concurrent writes
            # (e.g. token refresh updating UserActivity.last_seen_at).
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

if DEBUG:
    # Local dev: serve assets from STATICFILES_DIRS without collectstatic.
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Sentry error reporting (optional, turned on only when SENTRY_DSN is set)
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', '').strip() or (
    'development' if DEBUG else 'production'
)
SENTRY_RELEASE = os.getenv('SENTRY_RELEASE', '').strip() or VERSION
SENTRY_TRACES_SAMPLE_RATE = _env_float('SENTRY_TRACES_SAMPLE_RATE', 0.0)

def _skip_production_config_validation() -> bool:
    """Allow key-generation tooling before JWT_ISSUER/JWT_AUDIENCE are configured."""
    return len(sys.argv) > 1 and sys.argv[1] == 'generate_jwt_keys'


if not DEBUG and not _skip_production_config_validation():
    _production_config_errors = []
    if not JWT_ISSUER:
        _production_config_errors.append('JWT_ISSUER is required when DEBUG=false.')
    if not JWT_AUDIENCE:
        _production_config_errors.append('JWT_AUDIENCE is required when DEBUG=false.')
    if _production_config_errors:
        raise ImproperlyConfigured('\n'.join(_production_config_errors))

from config.scim_settings import SCIM_SERVICE_PROVIDER

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    from config.sentry_scrub import before_breadcrumb, before_send, event_scrubber

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            LoggingIntegration(
                level=logging.INFO,
                event_level=logging.ERROR,
            ),
        ],
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        send_default_pii=False,
        attach_stacktrace=True,
        # Strip query strings, request bodies, the Referer and secret-named locals.
        before_send=before_send,
        before_breadcrumb=before_breadcrumb,
        event_scrubber=event_scrubber(),
    )

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'config.request_context.RequestIdFilter',
        },
    },
    'formatters': {
        'console': {
            'format': '{asctime} {levelname} [{name}] [req={request_id}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'console',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # 5xx as ERROR and 4xx as WARNING, including when DEBUG=false.
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # DisallowedHost, CSRF failures and other security warnings.
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'config': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # Celery's own DEBUG output is internals only, so it stops at INFO.
        'celery': {
            'handlers': ['console'],
            'level': 'INFO' if LOG_LEVEL == 'DEBUG' else LOG_LEVEL,
            'propagate': False,
        },
        # "Task received" and "Task succeeded" lines every minute are noise. Failures
        # are still logged as errors. LOG_LEVEL=DEBUG shows them.
        'celery.app.trace': {
            'handlers': ['console'],
            'level': 'INFO' if LOG_LEVEL == 'DEBUG' else 'WARNING',
            'propagate': False,
        },
        'celery.worker.strategy': {
            'handlers': ['console'],
            'level': 'INFO' if LOG_LEVEL == 'DEBUG' else 'WARNING',
            'propagate': False,
        },
    },
}
