"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

from apps.authapi.jwks import read_jwt_env, resolve_jwt_configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _env_csv(name, default):
    raw = os.getenv(name, '').strip()
    if not raw:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv('SECRET_KEY', '').strip()
if not _secret_key:
    raise ImproperlyConfigured(
        '\n'
        'SECRET_KEY is not set — identity-service cannot start.\n'
        '\n'
        'Django uses this value to sign sessions and CSRF tokens. '
        'When JWT_PRIVATE_KEY is set, JWTs are signed with RS256 instead.\n'
        '\n'
        'How to fix:\n'
        '  1. Copy the example env file:\n'
        '       cp .env.example .env\n'
        '  2. Set SECRET_KEY in .env (or export it in your shell).\n'
        '  3. Generate a strong key:\n'
        '       python -c "from django.core.management.utils import '
        'get_random_secret_key; print(get_random_secret_key())"\n'
        '\n'
        'With Docker Compose, define SECRET_KEY in your .env file before '
        'running docker compose up.\n'
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').strip().lower() in {'1', 'true', 'yes', 'on'}

# Comma-separated; use * for all hosts only in trusted networks. Example: app.example.com,127.0.0.1
ALLOWED_HOSTS = _env_csv('ALLOWED_HOSTS', ('localhost', '127.0.0.1'))
# Full origins with scheme (required for cross-site POST / CSRF). Example: https://app.example.com
CSRF_TRUSTED_ORIGINS = _env_csv(
    'CSRF_TRUSTED_ORIGINS',
    (
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:4000',
        'http://127.0.0.1:4000',
        'http://localhost:5174',
        'http://127.0.0.1:5174',
    ),
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

VERSION = '0.2.0'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'apps.authapi',
    'apps.companies',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.authapi.authentication.ShellUIJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.authapi.permissions.ShellUIPermission',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'ShellUI Auth API',
    'DESCRIPTION': (
        'API documentation. Use **Authorize** and enter `Bearer <token>` or paste the raw JWT; '
        'Swagger sends `Authorization: Bearer …` for operations that require **bearerAuth**.'
    ),
    'VERSION': VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'TAGS': [
        {'name': 'auth-session', 'description': 'Session lifecycle endpoints (settings, token refresh, logout, JWKS).'},
        {'name': 'auth-social', 'description': 'OAuth/social login flow endpoints.'},
        {'name': 'auth-profile', 'description': 'Current authenticated user profile and metadata.'},
        {'name': 'auth-preferences', 'description': 'Current authenticated user preferences.'},
        {'name': 'directory-users', 'description': 'User directory management for staff/company owners.'},
        {'name': 'directory-groups', 'description': 'Group management for staff/company owners.'},
        {'name': 'oauth-clients', 'description': 'Company OAuth client mappings.'},
        {'name': 'oauth-social-apps', 'description': 'SocialApp key catalog and setup flows.'},
        {'name': 'audit-events', 'description': 'Login audit events and filters.'},
        {'name': 'platform-metrics', 'description': 'Prometheus metrics endpoints.'},
        {'name': 'personal-access-tokens', 'description': 'User-personal JWT access tokens (read-only or read/write).'},
        {'name': 'companies', 'description': 'Company membership and company settings endpoints.'},
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

_jwt_env = read_jwt_env()
_jwt_config = resolve_jwt_configuration(
    secret_key=SECRET_KEY,
    debug=DEBUG,
    **_jwt_env,
)
JWT_ALGORITHM = _jwt_config['algorithm']
JWT_ACTIVE_KEY_ID = _jwt_config['active_key_id']
JWT_SIGNING_KEY = _jwt_config['signing_key_obj']
JWT_PREVIOUS_VERIFYING_KEYS = _jwt_config['previous_verifying_keys']
JWT_ACCEPT_HS256_LEGACY = _jwt_config['accept_hs256_legacy']
JWKS_ENABLED = _jwt_config['jwks_enabled']
JWT_REQUIRES_RS256 = _jwt_config['requires_rs256']

SIMPLE_JWT.update(
    {
        'ALGORITHM': JWT_ALGORITHM,
        'SIGNING_KEY': _jwt_config['signing_key'],
        'VERIFYING_KEY': _jwt_config['verifying_key'],
    }
)

# Personal access tokens (PAT): JWT access token lifetime when creating a PAT (see views._issue_personal_access_token).
PERSONAL_ACCESS_TOKEN_LIFETIME = timedelta(days=90)

GITHUB_CLIENT_ID = os.getenv('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.getenv('GITHUB_CLIENT_SECRET', '')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
MICROSOFT_CLIENT_ID = os.getenv('MICROSOFT_CLIENT_ID', '')
MICROSOFT_CLIENT_SECRET = os.getenv('MICROSOFT_CLIENT_SECRET', '')

# Optional MaxMind GeoLite2/GeoIP2 City database (.mmdb) for login audit country/city.
# Install: pip install geoip2  — then set path to your .mmdb file.
SHELLUI_GEOIP_DATABASE_PATH = os.getenv('SHELLUI_GEOIP_DATABASE_PATH', '')

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'APPS': [
            {
                'client_id': GITHUB_CLIENT_ID,
                'secret': GITHUB_CLIENT_SECRET,
                'key': '',
            }
        ],
        'SCOPE': ['read:user', 'user:email'],
    },
    'google': {
        'APPS': [
            {
                'client_id': GOOGLE_CLIENT_ID,
                'secret': GOOGLE_CLIENT_SECRET,
                'key': '',
            }
        ],
        'SCOPE': ['openid', 'email', 'profile'],
    },
    'microsoft': {
        'APPS': [
            {
                'client_id': MICROSOFT_CLIENT_ID,
                'secret': MICROSOFT_CLIENT_SECRET,
                'key': '',
            }
        ],
        'SCOPE': ['openid', 'email', 'profile', 'User.Read'],
        'TENANT': 'common',
    },
}

# Cross-origin: ShellUI app, admin iframe (Vite), and optional extra origins from env
# (comma-separated), e.g. CORS_ALLOWED_ORIGINS=https://app.example.com,https://admin.example.com
CORS_ALLOWED_ORIGINS = [
    'http://localhost:4000',
    'http://127.0.0.1:4000',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]
for _origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(','):
    _origin = _origin.strip()
    if _origin and _origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_origin)

CORS_ALLOW_CREDENTIALS = True

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

POSTGRES_DATABASE_URL = os.getenv('POSTGRES_DATABASE_URL', '').strip()

if POSTGRES_DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            POSTGRES_DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
