#!/usr/bin/env python3
"""Write config/allauth_provider_apps.py from the provider catalog (supported entries only)."""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / 'apps' / 'authapi' / 'provider_catalog.json'
OUT_PATH = ROOT / 'config' / 'allauth_provider_apps.py'


def main() -> int:
    if not CATALOG_PATH.is_file():
        print(f'Missing catalog: {CATALOG_PATH}', file=sys.stderr)
        return 1
    catalog = json.loads(CATALOG_PATH.read_text(encoding='utf-8'))
    apps: set[str] = set()
    for entry in catalog.get('providers') or []:
        if not entry.get('supported'):
            continue
        app_path = str(entry.get('app') or '').strip()
        if app_path.startswith('allauth.socialaccount.providers.'):
            apps.add(app_path)
    ordered = sorted(apps)
    lines = [
        '"""Installed django-allauth socialaccount provider apps (generated)."""',
        '',
        '# Generated by tools/generate_allauth_provider_apps.py — do not edit by hand.',
        'ALLAUTH_SOCIALACCOUNT_PROVIDER_APPS: tuple[str, ...] = (',
    ]
    for app in ordered:
        lines.append(f"    '{app}',")
    lines.append(')')
    lines.append('')
    OUT_PATH.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {len(ordered)} supported provider apps to {OUT_PATH}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
